# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6414d991deaa1fb086c0a2e16a18707c8be271e5aa21fe8ced53646bd6caec4d63aade4d9111ed323953c4d474e1f7880647b28280f3845f2381d7532bed4eb

test:
  secret_key_base: 2ab048a63436c33dbf387629ecb165427d38f9c5344045667735cb41b128e40ea2ccc78dd5fdefc3a4e50a1c9c5b1b0f0027900c8db161da82465f1c817523bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
